
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
        uv pip install pytest black isort

    - name: Run isort
      run: |
        source .venv/bin/activate
        isort --check --diff .

    - name: Run black
      run: |
        source .venv/bin/activate
        black --check .

    - name: Run pytest
      run: |
        source .venv/bin/activate
        pytest
